### ISSUE TITLE
Is it possible to support VS 2013?

### ISSUE THREAD

**Issue by jasjuang** [mrdooz/TabGroupJumperVSIX#1]
I still can't upgrade to VS 2015 yet because the lack of CUDA support. Would it be possible for you to provide a version that works with VS 2013?

**Comment by mrdooz** [comment]
Hey, I hadn't seen this comment until now. Does the non-VSIX version work for you? https://github.com/mrdooz/TabGroupJumper

**Comment by jasjuang** [comment]
It doesn't work for me. Looks like that only supports Visual Studio 2012

**Comment by jasjuang** [comment]
I am using VS 2017 now.
